Kubernetes templating
otus-kuber-2020-07/enzo1920_platform pull request #7
Opened 2020-09-15 13:35 UTC by enzo1920

# Выполнено ДЗ №6

Выполнены задания по методичке.
На разных шагах врозникали проблемы
пока не разобрался с kubecfg(почему генерит не ту версию)
Отправляю на проверку
## PR checklist:
 - [*] Выставлен label с темой домашнего задания

2020-09-20 13:43 UTC, Jasstkn commented on kubernetes-templating/kubecfg/services.jsonnet
> +local kube = import "https://github.com/bitnami-labs/kube-libsonnet/raw/52ba963ca44f7a4960aeae9ee0fbee44726e481f/kube.libsonnet";
Смотрите, по этой ссылке у вас открывается спека по классу kube, можете посмотреть, что там действительно версия деплоймента старая. 
Обновитесь до версии, которая последняя по мастеру: 
`https://raw.githubusercontent.com/bitnami-labs/kube-libsonnet/master/kube.libsonnet`

Плюс вам нужно указать имя порта: `ports: [{name: "http", containerPort: 50051}],`так как в последней версии это обязательный параметр. После этого все должно зарендериться с последними версиями :)

2020-09-20 13:45 UTC, Jasstkn requested changes
Добрый день. Написала вам комментарий по kubecfg, жду исправленный вариант :)

2020-09-20 13:48 UTC, enzo1920 commented on kubernetes-templating/kubecfg/services.jsonnet
> +local kube = import "https://github.com/bitnami-labs/kube-libsonnet/raw/52ba963ca44f7a4960aeae9ee0fbee44726e481f/kube.libsonnet";
Ок, спасибо! Сделаю, небольшие тех проблемы с сервером

2020-09-23 13:22 UTC, enzo1920 commented on kubernetes-templating/kubecfg/services.jsonnet
> +local kube = import "https://github.com/bitnami-labs/kube-libsonnet/raw/52ba963ca44f7a4960aeae9ee0fbee44726e481f/kube.libsonnet";
поправил, сам kubecfg поставил не через brew(фу блин), а через исходники

2020-09-23 13:32 UTC, enzo1920 commented on kubernetes-templating/kubecfg/services.jsonnet
> +local kube = import "https://github.com/bitnami-labs/kube-libsonnet/raw/52ba963ca44f7a4960aeae9ee0fbee44726e481f/kube.libsonnet";
шоп вроде как работает

2020-09-23 13:32 UTC, enzo1920 commented on kubernetes-templating/kubecfg/services.jsonnet
> +local kube = import "https://github.com/bitnami-labs/kube-libsonnet/raw/52ba963ca44f7a4960aeae9ee0fbee44726e481f/kube.libsonnet";
спасибо за подсказку!

2020-09-23 18:26 UTC, Jasstkn approved these changes
Добрый день. Здорово, что разобрались - домашка принята!

2020-09-23 18:26 UTC, merged