Kubernetes operators
otus-kuber-2020-07/enzo1920_platform pull request #8
Opened 2020-10-14 09:02 UTC by enzo1920

# Выполнено ДЗ №2

 - по методичке выполнены основные и дополнительные задания со *
 - добавлены образы на хаб, из первого дз, со * собран образ для frontend,paymentservice
## Как запустить проект:
 - с

## Как проверить работоспособность:
  - скачать yaml и применить в kuber

## В процессе сделано:
 - Пункт 1
   По ответу на вопрос: почему обновление ReplicaSet не повлекло обновление запущенных pod?
   Из лекции: ReplicaSet не умеет рестартовать запущенные поды при обновлении шаблона.
   Думаю по этому не повлекло обновление запущенных pod.
## PR checklist:
 - [*] Выставлен label с темой домашнего задания

2020-10-14 09:04 UTC, enzo1920 commented
так))) у меня как обычно все пошло не так. Все делал по шагам, потом уже когда развернул докер оператор  некоторые поды в состоянии pending  висят . Задание делал как кластере kind , уже раза 3 все сносил и проходил по шагам сначала и всегда этот pending. в евентах:

4m9s        Normal    ExternalProvisioning   persistentvolumeclaim/backup-mysql-instance-pvc   waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
105s        Warning   FailedScheduling       pod/mysql-instance-6785949c48-hlxkb               error while running "VolumeBinding" prebind plugin for pod "mysql-instance-6785949c48-hlxkb": Failed to bind volumes: timed out waiting for the condition
4m9s        Normal    ExternalProvisioning   persistentvolumeclaim/mysql-instance-pvc          waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
6m57s       Warning   FailedScheduling       pod/restore-mysql-instance-job-ggg5x              error while running "VolumeBinding" prebind plugin for pod "restore-mysql-instance-job-ggg5x": Failed to bind volumes: timed out waiting for the condition

2020-10-16 06:28 UTC, Jasstkn commented
> так))) у меня как обычно все пошло не так. Все делал по шагам, потом уже когда развернул докер оператор некоторые поды в состоянии pending висят . Задание делал как кластере kind , уже раза 3 все сносил и проходил по шагам сначала и всегда этот pending. в евентах:
> 
> 4m9s Normal ExternalProvisioning persistentvolumeclaim/backup-mysql-instance-pvc waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
> 105s Warning FailedScheduling pod/mysql-instance-6785949c48-hlxkb error while running "VolumeBinding" prebind plugin for pod "mysql-instance-6785949c48-hlxkb": Failed to bind volumes: timed out waiting for the condition
> 4m9s Normal ExternalProvisioning persistentvolumeclaim/mysql-instance-pvc waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
> 6m57s Warning FailedScheduling pod/restore-mysql-instance-job-ggg5x error while running "VolumeBinding" prebind plugin for pod "restore-mysql-instance-job-ggg5x": Failed to bind volumes: timed out waiting for the condition

у вас вольюм не может создаться. попробуйте в гке делать или включите в миникубе minikube addons list 
> storage-provisioner

2020-10-16 06:31 UTC, Jasstkn requested changes
Разберитесь с провиженингом вольюмов в кластере. Если нет дефолтного сторадж класса, то скорее всего ничего не заработает. Предлагаю вам в миникубе или в гке попробовать

2020-10-25 17:53 UTC, Jasstkn commented on kubernetes-operators/build/templates/backup-pvc.yml.j2
> +      pv-usage: "backup-{{ name }}"
в гке запрещено использовать селекторы: https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes

2020-10-25 18:08 UTC, Jasstkn commented on kubernetes-operators/build/templates/backup-pvc.yml.j2
> +      pv-usage: "backup-{{ name }}"
у кайнда те же ошибки:
```
  Normal   WaitForPodScheduled   15s               persistentvolume-controller                                                                         waiting for pod restore-mysql-instance-job-c95wf to be scheduled
  Normal   Provisioning          13s               rancher.io/local-path_local-path-provisioner-78776bfc44-n4zjn_6ab6549f-3bec-4fa8-984e-a0d8764ade18  External provisioner is provisioning volume for claim "default/backup-mysql-instance-pvc"
  Warning  ProvisioningFailed    13s               rancher.io/local-path_local-path-provisioner-78776bfc44-n4zjn_6ab6549f-3bec-4fa8-984e-a0d8764ade18  failed to provision volume with StorageClass "standard": claim.Spec.Selector is not supported
  Normal   ExternalProvisioning  5s (x3 over 13s)  persistentvolume-controller                                                                         waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator
```

2020-10-26 08:04 UTC, enzo1920 commented on kubernetes-operators/build/templates/backup-pvc.yml.j2
> +      pv-usage: "backup-{{ name }}"
Привет, я посмотрел питоновский код оператора и у меня вопрос: если я удалю из темплейтов селекторы, то возможно job  не будет удалятся, верно?

2020-10-27 08:22 UTC, Jasstkn commented on kubernetes-operators/build/templates/backup-pvc.yml.j2
> +      pv-usage: "backup-{{ name }}"
По идее будет, почему нет?

2020-10-28 13:31 UTC, enzo1920 commented on kubernetes-operators/build/templates/backup-pvc.yml.j2
> +      pv-usage: "backup-{{ name }}"
нет , все также. Удалил лейблы и селекторы из шаблонов.
Так не работает  в гке
`28m         Normal    ProvisioningSucceeded    persistentvolumeclaim/backup-mysql-instance-pvc   Successfully provisioned volume pvc-264604c3-eb40-402e-9fc0-e55329210e5b using kubernetes.io/gce-pd
28m         Normal    Logging                  mysql/mysql-instance                              Creation event is processed: 1 succeeded; 0 failed.
28m         Normal    Logging                  mysql/mysql-instance                              Handler 'mysql_on_create' succeeded.
28m         Warning   FailedScheduling         pod/mysql-instance-546bb4c477-fww4r               pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
28m         Normal    Scheduled                pod/mysql-instance-546bb4c477-fww4r               Successfully assigned default/mysql-instance-546bb4c477-fww4r to gke-cluster-z29-default-pool-b9a53fb0-q11x
28m         Normal    SuccessfulAttachVolume   pod/mysql-instance-546bb4c477-fww4r               AttachVolume.Attach succeeded for volume "pvc-77a0ade3-0094-430b-bf0c-acafd893feb0"
28m         Normal    Pulling                  pod/mysql-instance-546bb4c477-fww4r               Pulling image "mysql:5.7"
28m         Normal    Pulled                   pod/mysql-instance-546bb4c477-fww4r               Successfully pulled image "mysql:5.7"
27m         Normal    Created                  pod/mysql-instance-546bb4c477-fww4r               Created container mysql-instance
27m         Normal    Started                  pod/mysql-instance-546bb4c477-fww4r               Started container mysql-instance
28m         Normal    SuccessfulCreate         replicaset/mysql-instance-546bb4c477              Created pod: mysql-instance-546bb4c477-fww4r
28m         Normal    ProvisioningSucceeded    persistentvolumeclaim/mysql-instance-pvc          Successfully provisioned volume pvc-77a0ade3-0094-430b-bf0c-acafd893feb0 using kubernetes.io/gce-pd
28m         Normal    ScalingReplicaSet        deployment/mysql-instance                         Scaled up replica set mysql-instance-546bb4c477 to 1
28m         Normal    Scheduled                pod/mysql-operator-67c466976c-s9zr9               Successfully assigned default/mysql-operator-67c466976c-s9zr9 to gke-cluster-z29-default-pool-b9a53fb0-q11x
28m         Normal    Pulling                  pod/mysql-operator-67c466976c-s9zr9               Pulling image "enzo1920/enzo1920k8s_operator:latest"
28m         Normal    Pulled                   pod/mysql-operator-67c466976c-s9zr9               Successfully pulled image "enzo1920/enzo1920k8s_operator:latest"
28m         Normal    Created                  pod/mysql-operator-67c466976c-s9zr9               Created container operator
28m         Normal    Started                  pod/mysql-operator-67c466976c-s9zr9               Started container operator
28m         Normal    SuccessfulCreate         replicaset/mysql-operator-67c466976c              Created pod: mysql-operator-67c466976c-s9zr9
28m         Normal    ScalingReplicaSet        deployment/mysql-operator                         Scaled up replica set mysql-operator-67c466976c to 1
28m         Warning   FailedScheduling         pod/restore-mysql-instance-job-bszpz              persistentvolumeclaim "backup-mysql-instance-pvc" not found
28m         Warning   FailedScheduling         pod/restore-mysql-instance-job-bszpz              pod has unbound immediate PersistentVolumeClaims (repeated 3 times)
28m         Normal    Scheduled                pod/restore-mysql-instance-job-bszpz              Successfully assigned default/restore-mysql-instance-job-bszpz to gke-cluster-z29-default-pool-b9a53fb0-q11x
28m         Normal    SuccessfulAttachVolume   pod/restore-mysql-instance-job-bszpz              AttachVolume.Attach succeeded for volume "pvc-264604c3-eb40-402e-9fc0-e55329210e5b"
26m         Normal    Pulled                   pod/restore-mysql-instance-job-bszpz              Container image "mysql:5.7" already present on machine
26m         Normal    Created                  pod/restore-mysql-instance-job-bszpz              Created container backup
26m         Normal    Started                  pod/restore-mysql-instance-job-bszpz              Started container backup
22m         Warning   BackOff                  pod/restore-mysql-instance-job-bszpz              Back-off restarting failed container
28m         Normal    SuccessfulCreate         job/restore-mysql-instance-job                    Created pod: restore-mysql-instance-job-bszpz
22m         Normal    SuccessfulDelete         job/restore-mysql-instance-job                    Deleted pod: restore-mysql-instance-job-bszpz
22m         Warning   BackoffLimitExceeded     job/restore-mysql-instance-job                    Job has reached the specified backoff limit
`

2020-11-11 20:02 UTC, Jasstkn approved these changes
Привет! Прогнала домашку в миникубе - все заехало, в кайнде отказывается работать - почему-то дальше pvc дело не идет (поды даже не создаются). Принимаю твою домашку, так как сама логика выполнена правильно, в особенности реализации pvc в кайнде не очень охота вдаваться. 👍

2020-11-11 20:02 UTC, merged